apiVersion: v1
kind: Service
metadata:
  name: calculator-api-service
  labels:
    app: calculator-api
spec:
  type: NodePort
  selector:
    app: calculator-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30080
